name: black

on: [push, pull_request]

# use workaround due to: https://github.com/psf/black/issues/2079#issuecomment-812359146
jobs:
    check-formatting:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
            - uses: psf/black@22.6.0
