name: Documentation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13
      - name: Update package index
        run: sudo apt-get update
      - name: Install Pandoc
        run: sudo apt-get -y install pandoc
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Make HTML Docs
        run: tox -e doc
      - name: deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: ${{ github.repository_owner }}/terrapower.github.io
          branch: main
          folder: doc/_build/html
          target-folder: dragon-plugin
