name: Documentation

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:    # Building and deploying docs is broken on forked repos
    if: github.repository == 'terrapower/dragon-armi-plugin'
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13
      - name: Update package index
        run: sudo apt-get update
      - name: Install Pandoc
        run: sudo apt-get -y install pandoc
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Make HTML Docs
        run: |
          pip install -U pip
          pip install -r requirements.txt
          pip install -e .[test,docs]
          cd doc
          make html
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: ${{ github.repository_owner }}/terrapower.github.io
          branch: main
          folder: doc/_build/html
          target-folder: dragon-plugin
