name: Dragon unit tests

permissions:
  contents: read

on:
  push:
    paths-ignore:
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'doc/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python: [3.11, 3.12, 3.13]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true
      - name: Run Tests
        run: |
          pip install -U pip
          pip install -r requirements.txt
          pip install -e .[test]
          pytest terrapower
