name: Dragon unit tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 2 1 * *"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.11, 3.12, 3.13]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Update package index
        run: sudo apt-get update
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e test
